abstract: Access compile-time hints at runtime
author: Audrey Tang <autrijus@autrijus.org>
build_requires:
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.50
license: perl
name: Devel-Hints
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
version: 0.11
